### ISSUE TITLE
get_queryset warning

### ISSUE THREAD

**Issue by blindpenguin** [praekelt/django-preferences#6]
There is a warning everytime the app is loaded. It doesn't break my system, but it's pretty annoying. Any chance to get an update? Thank you.

`/usr/local/lib/python2.7/dist-packages/django_preferences-0.0.6-py2.7.egg/preferences/managers.py:6: RemovedInDjango18Warning: SingletonManager.get_query_set method should be renamed get_queryset`

**Comment by cblignaut** [comment]
Thanks this was fixed in the latest release, https://pypi.org/project/django-preferences/
